#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# PNG to ICO Converter - GUI Wrapper

set -e

echo "========================================"
echo "Starting Development Environment"
echo "PNG to ICO Converter - GUI Wrapper"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if virtual environment exists
if [ ! -d "venv" ]; then
    echo -e "${YELLOW}Virtual environment not found. Creating...${NC}"
    python -m venv venv
    echo -e "${GREEN}Virtual environment created${NC}"
fi

# Activate virtual environment
echo "Activating virtual environment..."
source venv/Scripts/activate  # Windows
# source venv/bin/activate  # Uncomment for Linux/macOS

# Install dependencies
echo "Installing dependencies..."
pip install -q -r requirements.txt

# Install tkinterdnd2 for drag-and-drop support
echo "Installing tkinterdnd2 for drag-and-drop support..."
pip install -q tkinterdnd2

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "To run the CLI converter:"
echo "  python ico_converter.py *.png"
echo ""
echo "To run the GUI wrapper:"
echo "  python gui_wrapper.py"
echo ""
echo "Features:"
echo "  - Drag and drop PNG files onto the GUI"
echo "  - Batch convert multiple files"
echo "  - Select custom icon sizes"
echo "  - Choose output directory"
echo ""
echo "========================================"
